config/routes.rb
Rails.application.routes.draw do
  concern :opinions_about do
    resources :comments
  end
  resources :rentals, concerns: :opinions_about
  resources :reservations
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  devise_scope :landlord do
    get '/landlord', to: 'rentals#new', as: 'landlord_root'
  end
  devise_scope :renter do
    get '/renter', to: 'reservations#new', as: 'renter_root'
  end
  resources :users, only: [], concerns: :opinions_about
end

app/models/rental.rb
class Rental < ActiveRecord::Base
  belongs_to :landlord, foreign_key: :user_id
  has_many :reservations
  has_many :renters, through: :reservations
  has_many :comments, as: :opinions_about
  validates :city, presence: true
  validates :state, presence: true
  validates :base_rate, presence: true
  has_attached_file :the_photo, :styles => { :small => "100x100>", :original => "400x400>>" }
  validates_attachment :the_photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  def set_default_fields(rental_hash)
    if rental_hash[:rental_type].nil?
      self.rental_type = "shared"
    else
      self.rental_type = rental_hash[:rental_type]
    end

    if rental_hash[:number_bedrooms].nil?
      self.number_bedrooms = 1
    else
      self.number_bedrooms = rental_hash[:number_bedrooms]
    end

    if rental_hash[:number_beds].nil?
      self.number_beds = 1
    else
      self.number_beds = rental_hash[:number_beds]
    end

    if rental_hash[:number_bathrooms].nil?
      self.number_bathrooms = 0
    else
      self.number_bathrooms = rental_hash[:number_bathrooms]
    end

    if rental_hash[:max_number_guests].nil?
      self.max_number_guests = 1
    else
      self.max_number_guests = rental_hash[:max_number_guests]
    end

    if rental_hash[:extra_guest_rate].nil?
      self.extra_guest_rate = 0
    else
      self.extra_guest_rate = rental_hash[:extra_guest_rate]
    end

    if rental_hash[:minimum_days_stay].nil?
      self.minimum_days_stay = 1
    else
      self.minimum_days_stay = rental_hash[:minimum_days_stay]
    end

    if rental_hash[:description].nil?
      self.description = ""
    else
      self.description = rental_hash[:description]
    end
    self
  end

private
  def rental_params
    params.require(:rental).permit(:rental_type, :city, :state, :number_bedrooms, :number_beds,
                                   :number_bathrooms, :max_number_guests, :base_rate,
                                   :extra_guest_rate, :minimum_days_stay, :description,
                                   :has_photo, :the_photo)
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

  def new
    @rental = Rental.new
  end

  def create
    @rental = Rental.new(params[:rental_params])
    @rental.city = params[:rental][:city]
    @rental.state = params[:rental][:state]
    @rental.base_rate = params[:rental][:base_rate]
    @rental.user_id = current_user.id
    if params[:rental][:has_photo]
      @rental.has_photo = true
      @rental.the_photo = params[:rental][:the_photo]
    end
    @rental.set_default_fields(params[:rental])
    if @rental.save
      flash[:notice] = "The rental has been saved"
      redirect_to rental_path(@rental.id )
    else
      render "new"
    end
  end

  def show
    @rental = Rental.find(params[:id])
  end

  def index
    if current_user.landlord?
      @rentals = Rental.where(:user_id => current_user.id).order(state: :asc, city: :asc)
    else
      @rentals = Rentals.all.order(state: :asc, city: :asc)
    end
  end

  def edit
    @rental = Rental.find(params[:id])
    if current_user.id != @rental.user_id
      redirect_to rental_path(@rental)
    end
  end

  def update
    @rental = Rental.find(params[:id])
    if current_user.id != @rental.user_id
      flash[:alert] = "You may only edit your own rentals"
      redirect_to rental_path(@rental)
    elsif !params[:rental].nil?
        if @rental.update(:rental_params)
          flash[:notice] = "The rental has been updated"
          redirect_to landlord_return_to_path
        else
          render 'edit'
        end
    else
      flash[:notice] = "Nothing was updated"
      redirect_to landlord_return_to_path
    end
  end

  def destroy
    @rental = Rental.find(params[:id])
    if current_user.id != @rental.user_id
      flash[:alert] = "You may only delete your own rentals"
      redirect_to rental_path(@rental)
    else
      @rental.destroy
      flash[:notice] = "The rental was deleted"
      redirect_to landlord_return_to_path
    end
  end
end

app/views/rentals/_form.html.haml
= render('layouts/errors', :object => @rental)
%br>/
%h5
  %b Please enter the information about your rental:
%br/
= form_for @rental, :html => { :multipart => true } do |f|
  .form-group
    = f.label :rental_type
    = f.label :rental_type, "Entire property", :value => "entire", :class => "label_short"
    = f.radio_button :rental_type, "entire", :class => "padding-right"
    = f.label :rental_type, "Private room", :value => "private", :class => "label_short"
    = f.radio_button :rental_type, "private", :class => "padding-right"
    = f.label :rental_type, "Shared room", :value => "shared", :class => "label_short"
    = f.radio_button :rental_type, "shared", :class => "padding-right"
  %br/
  .form-group
    = f.label :city, :class => "label_short"
    = f.text_field :city, :class => "padding-right text_field"
    = f.label :state, :class => "label_short"
    = f.select(:state, options_for_select(us_states, @rental.state))
  .form-group
    = f.label :number_bedrooms, "Bedroom count (max:\u00a010)", :class => "label_short"
    = f.number_field :number_bedrooms, in: 1..10, :class => "margin_right_30"
    = f.label :number_beds, "Bed count (max:\u00a020)", :class => "label_short"
    = f.number_field :number_beds, in: 1..20, :class => "margin_right_30"
    = f.label :number_bathrooms, "Bathroom count (max:\u00a010)", :class => "label_short"
    = f.number_field :number_bathrooms, in: 1..10, :class => "margin_right_30"
    = f.label :max_number_guests, "Maximum number of guests (max:\u00a020)", :class => "label_short"
    = f.number_field :max_number_guests, in: 1..20
  .form-group
    = f.label :base_rate, "Rate/night/1 guest $USD (max:\u00a0$5000)", :class => "label_short"
    = f.number_field :base_rate, in: 1..5000, :class => "margin_right_20"
    = f.label :extra_guest_rate, "Rate/night/extra guest $USD (max:\u00a0$1000)", :class => "label_short"
    = f.number_field :extra_guest_rate, in: 1..1000, :class => "margin_right_20"
    = f.label :minimum_days_stay, "Minimum stay length in days (max:\u00a0365)", :class => "label_short"
    = f.number_field :minimum_days_stay, in: 1..365
  .form-group
    = f.label :description
    = f.text_area :description, rows: 10, cols: 140
  #has-photo.form-group
    = f.label :has_photo, "Do you want to upload a photo?"
    = f.check_box :has_photo
  %br/
  %br/
  #upload.form-group
    = f.file_field :the_photo
  %br/
  = f.submit "Create Rental", :class => "btn btn-primary pull_left"

app/views/rentals/_form_d.html.erb
<%= render('layouts/errors', :object => @rental) %>
<h5><b><br>Please enter the information about your rental:</b></h5>
<div class = "form-group">
  <%= f.label :rental_type %>
  <%= f.label :rental_type, "Entire property", :value => "entire", :class => "label_short"  %>
  <%= f.radio_button :rental_type, "entire", :class => "padding-right", disabled %>
  <%= f.label :rental_type, "Private room", :value => "private", :class => "label_short" %>
  <%= f.radio_button :rental_type, "private", :class => "padding-right", disabled %>
  <%= f.label :rental_type, "Shared room", :value => "shared", :class => "label_short" %>
  <%= f.radio_button :rental_type, "shared", :class => "padding-right", disabled %>
</div><br><br>
<div class = "form-group">
  <%= f.label :city, :class => "label_short" %>
  <%= f.text_field :city, :class => "padding-right", disabled %>
  <%= f.label :state, :class => "label_short" %>
  <%= f.select(:state, options_for_select(us_states, @rental.state)), :class => "padding-right", disabled %>
</div>
<div class="form-group">
  <%= f.label :number_bedrooms, "Bedroom count", :class => "label_short" %>
  <%= f.number_field :number_bedrooms, @rental.number_bedrooms, :class => "padding-right", disabled %>
  <%= f.label :number_beds, "Bed count", :class => "label_short" %>
  <%= f.number_field :number_beds, @rental.number_beds, in: 1..20, :class => "padding-right", disabled %>
  <%= f.label :number_bathrooms, "Bathroom count", :class => "label_short" %>
  <%= f.number_field :number_bathrooms, @rental.number_bathrooms, in: 1..10, :class => "padding-right", disabled %>
  <%= f.label :max_number_guests, "Maximum number of guests allowed" %>
  <%= f.number_field :max_number_guests, @rental.max_number_guests, in: 1..20, :class => "padding-right", disabled %>
</div>
<div class="form-group">
  <%= f.label :base_rate, "Nightly rate $USD for 1 guest" %>
  <%= f.number_field, :base_rate, @rental.base_rate, min: 10, :class => "padding-right", disabled %>
  <%= f.label :extra_guest_rate, "Nightly rate $USD per extra guest" %>
  <%= f.number_field, :extra_guest_rate, @rental.extra_guest_rate, min: 0, :class => "padding-right", disabled %>
  <%= f.label :minimum_days_stay, "Minimum stay length in days" %>
  <%= f.number_field, :minimum_days_stay, @rental.minimum_days_stay, min: 1, :class => "padding-right", disabled %>
</div>
<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, @rental.description, rows: 10, cols: 80, disabled %>
</div>
<br><br>

app/views/rentals/edit.html.erb
<% content_for(:title, "Edit Rental | Cindy's Airbnb!") %>
<h3><u>Edit a Rental</u></h3>
<%= image_tag @photo.the_photo.url(:original), :class => "center-block" %>
<%= form_for @rental, :html => { :multipart => true } do |f| %>

  <%= render('form') %>
  <%= f.submit "Update Rental", :class => "btn btn-warning pull_left" %>
<% end %>
  <p><%= link_to "Delete Rental", rental_path(@rental),
                       :data => {:confirm => "Please confirm the deletion of this rental",
                                 :method => "delete"},
                       :class => "btn btn-danger" %></p>
<br><br>

<h4><%= link_to "See All of Your Rentals", photos_path %></h4>
<h4><%= link_to "Create a New Rental", new_rental_path %></h4>
<h4><%= link_to "Logout", session_path("current"), :method => "delete" %></h4>

app/views/rentals/index.html.erb
<% content_for(:title, "All Photos | Share Your Photos!") %>
<div class='container'>
  <h3><u>Show All Photos</u></h3>
    <% @photos.each do |photo| %>
      <ul>
        <li><h5><%= link_to (image_tag photo.the_photo.url(:small), :class => 'pull_left'), edit_photo_path(photo) %>&nbsp&nbspcontributed by <%= photo.user.email %></h5></li>
      </ul>
    <% end %>
  <br><br>

  <div class="col-md-4">
    <hr>
    <h4><%= link_to "Add a New Photo", new_photo_path %></h4>
    <h4><%= link_to "See Your Profile", user_path(current_user.id) %></h4>
    <h4><%= link_to "Logout", session_path("current"), :method => "delete" %></h4>
  </div>
</div>

app/views/rentals/new.html.erb
<% content_for(:title, "New Rental | Cindy's Airbnb!") %>
<h3><u>Create a New Rental</u></h3>
  <%= render ('form') %>
<br><br><br>
<hr>
<h4><%= link_to "See All Rentals", rentals_path %></h4>
<h4><%= link_to "Log out", destroy_user_session_path, method: :delete %></h4>

app/views/rentals/new.html.haml
- content_for(:title, "New Rental | Cindy's Airbnb!")
%h3
  %u Create a New Rental
= render('form')
%br/
%br/
%br/
%hr/
%h4
  = link_to "See All Rentals", rentals_path
%h4
  = link_to "Log out", destroy_user_session_path, method: :delete

app/views/rentals/show.html.erb
<% content_for(:title, "Show a Rental | Cindy's Airbnb!") %>
<h3><u>Show a Rental</u></h3>
<%= image_tag @photo.the_photo.url(:original), :class => "center-block" %>
<%= render('form_d') %>
<br><br><br>
<hr>
<% if current_user.landlord? %>
  <h4><%= link_to "See All of Your Rentals", photos_path %></h4>
  <h4><%= link_to "Add a New Rental", new_rental_path %></h4>
<% else %>
  <h4><%= link_to "See All Rentals", photos_path %></h4>
<% end %>
<h4><%= link_to "Logout", session_path("current"), :method => "delete" %></h4>